[package]
name = "awgen"
description = "The Awgen game engine."
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy_egui = "0.33.0"
bevy_framepace = "0.18.0"
tinyfiledialogs = "3.9.1"
deno_core = { version = "0.323.0", default-features = false }
rustyscript = { version = "0.11", default-features = false }
serde_json = "1"
smol = "2"
thiserror = "2"

# https://github.com/rscarson/rustyscript/issues/332
deno_media_type = "=0.2.6"
